import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy policy for Westfield Elementary PTO website. Learn how we collect, use, and protect your information.",
  openGraph: {
    title: "Privacy Policy | Westfield Elementary PTO",
    description: "Privacy policy for Westfield Elementary PTO website. Learn how we collect, use, and protect your information.",
  },
  twitter: {
    title: "Privacy Policy | Westfield Elementary PTO",
    description: "Privacy policy for Westfield Elementary PTO website. Learn how we collect, use, and protect your information.",
  },
};

export default function PrivacyPolicyPage() {
  const lastUpdated = "December 10, 2024";

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <section className="bg-primary text-white py-12 lg:py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="text-3xl lg:text-4xl font-bold font-[family-name:var(--font-playfair)]">
            Privacy Policy
          </h1>
          <p className="mt-4 text-white/80">
            Last updated: {lastUpdated}
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-12 lg:py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white rounded-xl shadow-sm border border-border p-6 lg:p-10">
            <div className="prose max-w-none text-muted">
              
              {/* Introduction */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Introduction
                </h2>
                <p className="leading-relaxed">
                  Westfield Elementary PTO (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. 
                  This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you 
                  visit our website <strong>westfieldpto.com</strong> (the &quot;Site&quot;). Please read this privacy policy carefully. 
                  If you do not agree with the terms of this privacy policy, please do not access the Site.
                </p>
              </div>

              {/* Information We Collect */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Information We Collect
                </h2>
                
                <h3 className="text-lg font-medium text-foreground mt-6 mb-3">Personal Information You Provide</h3>
                <p className="leading-relaxed mb-4">
                  We may collect personal information that you voluntarily provide when you:
                </p>
                <ul className="list-disc pl-6 space-y-2 mb-4">
                  <li>Subscribe to our newsletter</li>
                  <li>Fill out volunteer interest forms</li>
                  <li>Contact us via email</li>
                  <li>Participate in PTO activities or events</li>
                </ul>
                <p className="leading-relaxed">
                  This information may include your name, email address, phone number, and your child&apos;s grade level.
                </p>

                <h3 className="text-lg font-medium text-foreground mt-6 mb-3">Information Collected Automatically</h3>
                <p className="leading-relaxed">
                  When you visit our Site, we automatically collect certain information about your device and your visit, including:
                </p>
                <ul className="list-disc pl-6 space-y-2 mt-4">
                  <li>Browser type and version</li>
                  <li>Operating system</li>
                  <li>Pages visited and time spent on pages</li>
                  <li>Referring website addresses</li>
                  <li>General geographic location (city/region level)</li>
                </ul>
              </div>

              {/* Google Analytics */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Google Analytics
                </h2>
                <p className="leading-relaxed mb-4">
                  We use Google Analytics, a web analytics service provided by Google, Inc. (&quot;Google&quot;). Google Analytics 
                  uses cookies to help us analyze how visitors use our Site. The information generated by the cookie about 
                  your use of the Site (including your IP address) will be transmitted to and stored by Google on servers 
                  in the United States.
                </p>
                <p className="leading-relaxed mb-4">
                  Google will use this information for the purpose of evaluating your use of the Site, compiling reports 
                  on website activity, and providing other services relating to website activity and internet usage. 
                  Google may also transfer this information to third parties where required to do so by law, or where 
                  such third parties process the information on Google&apos;s behalf.
                </p>
                <p className="leading-relaxed">
                  You can opt-out of Google Analytics by installing the{" "}
                  <a 
                    href="https://tools.google.com/dlpage/gaoptout" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="text-primary hover:text-primary-dark underline"
                  >
                    Google Analytics Opt-out Browser Add-on
                  </a>.
                </p>
              </div>

              {/* Email Marketing - Mailchimp */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Email Marketing (Mailchimp)
                </h2>
                <p className="leading-relaxed mb-4">
                  We use Mailchimp as our email marketing platform. When you subscribe to our newsletter or volunteer 
                  interest list, your information (including email address, name, and any other information you provide) 
                  is transferred to Mailchimp for processing in accordance with their{" "}
                  <a 
                    href="https://mailchimp.com/legal/privacy/" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="text-primary hover:text-primary-dark underline"
                  >
                    Privacy Policy
                  </a>{" "}
                  and{" "}
                  <a 
                    href="https://mailchimp.com/legal/terms/" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="text-primary hover:text-primary-dark underline"
                  >
                    Terms of Service
                  </a>.
                </p>
                <p className="leading-relaxed">
                  You can unsubscribe from our email list at any time by clicking the &quot;unsubscribe&quot; link 
                  at the bottom of any email we send, or by contacting us directly.
                </p>
              </div>

              {/* Cookies */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Cookies and Tracking Technologies
                </h2>
                <p className="leading-relaxed mb-4">
                  Our Site may use cookies, web beacons, and other tracking technologies to enhance your experience. 
                  Cookies are small data files stored on your device that help us improve our Site and your experience.
                </p>
                <p className="leading-relaxed mb-4">
                  <strong>Types of cookies we use:</strong>
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    <strong>Analytics Cookies:</strong> These help us understand how visitors interact with our Site 
                    by collecting and reporting information anonymously (Google Analytics).
                  </li>
                  <li>
                    <strong>Functional Cookies:</strong> These enable enhanced functionality and personalization.
                  </li>
                </ul>
                <p className="leading-relaxed mt-4">
                  You can control cookies through your browser settings. However, disabling cookies may affect some 
                  features of the Site.
                </p>
              </div>

              {/* How We Use Your Information */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  How We Use Your Information
                </h2>
                <p className="leading-relaxed mb-4">
                  We use the information we collect to:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Send you newsletters, event announcements, and PTO updates</li>
                  <li>Respond to your inquiries and requests</li>
                  <li>Coordinate volunteer activities and opportunities</li>
                  <li>Improve our website and communications</li>
                  <li>Analyze website usage to better serve our community</li>
                  <li>Comply with legal obligations</li>
                </ul>
              </div>

              {/* Information Sharing */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Information Sharing
                </h2>
                <p className="leading-relaxed mb-4">
                  We do not sell, trade, or rent your personal information to third parties. We may share your 
                  information only in the following circumstances:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    <strong>Service Providers:</strong> With trusted third-party services that help us operate our 
                    Site (such as Google Analytics and Mailchimp), subject to confidentiality agreements.
                  </li>
                  <li>
                    <strong>School Coordination:</strong> With Westfield Elementary School staff when necessary 
                    to coordinate PTO events and activities.
                  </li>
                  <li>
                    <strong>Legal Requirements:</strong> When required by law or to protect our rights and safety.
                  </li>
                </ul>
              </div>

              {/* Data Security */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Data Security
                </h2>
                <p className="leading-relaxed">
                  We implement reasonable security measures to protect your personal information. However, no method 
                  of transmission over the Internet or electronic storage is 100% secure. While we strive to protect 
                  your information, we cannot guarantee its absolute security.
                </p>
              </div>

              {/* Children's Privacy */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Children&apos;s Privacy
                </h2>
                <p className="leading-relaxed">
                  Our Site is intended for parents, teachers, and adult community members. We do not knowingly collect 
                  personal information from children under 13 years of age. If you believe we have collected information 
                  from a child under 13, please contact us immediately so we can delete such information.
                </p>
              </div>

              {/* Your Rights */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Your Rights
                </h2>
                <p className="leading-relaxed mb-4">
                  You have the right to:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Access the personal information we hold about you</li>
                  <li>Request correction of inaccurate information</li>
                  <li>Request deletion of your personal information</li>
                  <li>Unsubscribe from our email communications at any time</li>
                  <li>Opt-out of analytics tracking</li>
                </ul>
                <p className="leading-relaxed mt-4">
                  To exercise any of these rights, please contact us using the information below.
                </p>
              </div>

              {/* Third-Party Links */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Third-Party Links
                </h2>
                <p className="leading-relaxed">
                  Our Site may contain links to third-party websites (such as the Linn-Mar School District, 
                  donation platforms, and social media). We are not responsible for the privacy practices 
                  of these external sites. We encourage you to review the privacy policies of any third-party 
                  sites you visit.
                </p>
              </div>

              {/* Changes to This Policy */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Changes to This Privacy Policy
                </h2>
                <p className="leading-relaxed">
                  We may update this Privacy Policy from time to time. Any changes will be posted on this page 
                  with an updated &quot;Last Updated&quot; date. We encourage you to review this Privacy Policy periodically 
                  for any changes.
                </p>
              </div>

              {/* Contact Us */}
              <div className="mb-4">
                <h2 className="text-xl font-semibold text-foreground font-[family-name:var(--font-playfair)] mb-4">
                  Contact Us
                </h2>
                <p className="leading-relaxed mb-4">
                  If you have any questions about this Privacy Policy or our data practices, please contact us:
                </p>
                <div className="bg-gray-50 rounded-xl p-6">
                  <p className="font-medium text-foreground mb-2">Westfield Elementary PTO</p>
                  <p className="mb-1">
                    Email:{" "}
                    <a 
                      href="mailto:westfieldpto@gmail.com" 
                      className="text-primary hover:text-primary-dark"
                    >
                      westfieldpto@gmail.com
                    </a>
                  </p>
                  <p>
                    Website:{" "}
                    <a 
                      href="https://westfieldpto.com" 
                      className="text-primary hover:text-primary-dark"
                    >
                      westfieldpto.com
                    </a>
                  </p>
                </div>
              </div>

            </div>
          </div>

          {/* Back Link */}
          <div className="mt-8 text-center">
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-muted hover:text-primary transition-colors"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
              </svg>
              Back to Home
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}

